# Generated by Django 5.2.12 on 2026-03-14 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=15, verbose_name='Cédula de ciudadanía')),
                ('primer_nombre', models.CharField(max_length=30, verbose_name='Primer Nombre')),
                ('segundo_nombre', models.CharField(blank=True, max_length=30, null=True, verbose_name='Segundo Nombre')),
                ('primer_apellido', models.CharField(max_length=30, verbose_name='Primer Apellido')),
                ('segundo_apellido', models.CharField(max_length=30, verbose_name='Segundo Apellido')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
                'constraints': [models.UniqueConstraint(fields=('cedula',), name='Cedula de ciudadania unica')],
            },
        ),
        migrations.CreateModel(
            name='InformacionGeografica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_dane_municipio', models.CharField(max_length=5, verbose_name='Código DANE Municipio')),
                ('nombre_municipio', models.CharField(max_length=50, verbose_name='Nombre Municipio')),
                ('codigo_dane_centro_poblado', models.CharField(max_length=8, verbose_name='Código DANE Centro Poblado')),
                ('nombre_centro_poblado', models.CharField(max_length=100, verbose_name='Nombre Centro Poblado')),
                ('barrio', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre del Barrio')),
                ('longitud', models.DecimalField(decimal_places=6, max_digits=8)),
                ('latitud', models.DecimalField(decimal_places=6, max_digits=8)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='contenido.persona')),
            ],
            options={
                'verbose_name': 'Información Geográfica de la Persona',
                'verbose_name_plural': 'Información Geográfica de las Personas',
            },
        ),
    ]
