# Generated by Django 5.2.12 on 2026-03-14 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='informacion_geografica',
        ),
        migrations.AddField(
            model_name='persona',
            name='informacion_geografica',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenido.informaciongeografica'),
        ),
    ]
