# Generated by Django 5.2.12 on 2026-03-14 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0002_remove_persona_informacion_geografica_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='tipo_familiar',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
